language: bash

services:
  - docker

script:
  - free -h
  - docker run -h rpmbuild-el7.fmi.fi -v $TRAVIS_BUILD_DIR:/src/smartmet-library-newbase --rm fmidev/rpmbuild:el7 smartmet-library-newbase

after_success:
  - echo "Success"
